# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Behzad Ardehei
title: Senior iOS Developer
email: behzad.ardeh.e@gmail.com
website: behzadardehei.github.io

# Social links
# twitter_username: facespics
github_username: behzadardehei
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: behzad-ardehei-3248b4111
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I aim to use my skills as an engineer and consultant to better the lives of others.

  I pursue this goal by building beautiful + impactful products, teaching others, and showing up for my communities.

  I am most skilled in: 
  <mark>iOS</mark>
  <mark>Swift</mark>
  <mark>Objective-C</mark>
  <mark>Architecture Patterns</mark>
  <mark>Cocoa framework</mark>
  <mark>RxSwift</mark>
  <mark>Fastlane</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Music
   - Study

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
